#!/usr/bin/env bash

gcc -o ./keygen ./keygen.c -Wall;
gcc -o ./otp_enc_d ./otp_enc_d.c -Wall;
gcc -o ./otp_dec_d ./otp_dec_d.c -Wall;
gcc -o ./otp_enc ./otp_enc.c -Wall;
gcc -o ./otp_dec ./otp_dec.c -Wall;
